### ISSUE TITLE
Enzyme: test suit failed due to unfound module css-emitter

### ISSUE THREAD

**Issue by hectorpla** [hectorpla/sq-puzzles#1]
● Test suite failed to run

    Cannot find module 'css-emitter' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/after-transition/index.js:2:15)

 FAIL  src/components/BoardComponent.test.tsx
  ● Test suite failed to run

    Cannot find module 'css-emitter' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/after-transition/index.js:2:15)

**Comment by hectorpla** [comment]
deprecated use of move.js, migrated to anime.js
